<testsuite name="Mocha Tests" tests="2" failures="0" errors="2" skipped="0" timestamp="Fri, 04 Nov 2022 00:07:32 GMT" time="0.282">
<testcase classname="Test 2 service 1" name="test 2" time="0.001"><failure>expected 1 to deeply equal 2

      + expected - actual

      -1
      +2
      
AssertionError: expected 1 to deeply equal 2
    at Context.&#x3C;anonymous&#x3E; (mocha-tests/fts-service-1/test-2.js:5:21)
    at processImmediate (node:internal/timers:466:21)</failure></testcase>
<testcase classname="Test 1 service 1" name="test 1" time="0.001"><failure>expected 1 to deeply equal 2

      + expected - actual

      -1
      +2
      
AssertionError: expected 1 to deeply equal 2
    at Context.&#x3C;anonymous&#x3E; (mocha-tests/fts-service-1/test-1.js:5:21)
    at processImmediate (node:internal/timers:466:21)</failure></testcase>
</testsuite>
